### ISSUE TITLE
EyeTribe: Error in 'calibration' 'pointend' request for new SDK 0.9.77

### ISSUE THREAD

**Issue by moltaire** [esdalmaijer/PyGaze#62]
I am pretty sure this is an issue on the EyeTribe side, but since I am not totally aware of all the inner workings, I wanted to leave this here as well:

On a Windows (7 and 8) machine, calibration using PyGaze crashes after the first calibration point.
The error thrown tells me that the `'calibration' 'pointend'` request returned `None`.

Everything else, except for calibration, seems to work fine: Logging messages to the tracker log, start & stop recording.

Here's my post in the eyetribe-forums, in case you want to follow up there.

http://theeyetribe.com/forum/viewtopic.php?f=9&t=605&p=2557&sid=229616157d158b5b2a54d31582438cb4#p2557

Thanks for coming up with PyGaze. It's absolutely great.

Felix

**Comment by martintall** [comment]
Hi guys,

Martin Tall from Eye Tribe here. I've done some debugging on the server side. The pointend request fails due to stricter validation of JSON in the version 0.9.77.

Json message received from PyTribe.py

{
   "category": "calibration",
   "request": "pointend",
}

The trailing comma after pointend is not valid json. When there's no "values" the request line should terminate without a comma.

**Comment by esdalmaijer** [comment]
Hi guys,

Thanks Felix (@moltaire) for flagging this up, and thanks Martin (@martintall) for debugging the issue. It should be solved with [this commit](https://github.com/esdalmaijer/PyGaze/commit/52d53d7452411915a03171c4308ecb4fb372cf2c).

Could you confirm whether it works for you? (I'm still on the old API, on which everything runs fine either way.)

Cheers,
Edwin
